version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Mật khẩu cho user root
      MYSQL_DATABASE: mydb               # Tên database sẽ được tạo
      MYSQL_USER: user                    # Tạo user mới
      MYSQL_PASSWORD: password            # Mật khẩu cho user mới
    ports:
      - "3306:3306"  # Map cổng của container với máy host
    volumes:
      - mysql_data:/var/lib/mysql  # Lưu trữ dữ liệu

volumes:
  mysql_data: