version: '3'
services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data: 
