version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer-container
    restart: always
    ports:
      - "8083:8080"  # Adminer chạy trên cổng 8083

volumes:
  postgres_data:
    driver: local  # Tạo volume lưu trữ dữ liệu PostgreSQL
